$ANSIBLE_VAULT;1.1;AES256
61663061613963653463386466373933353435326535376165636338303136663963303461326538
6537653364336433326637383163666230373334346330630a653832326636346463373433376262
34653639353562306663623733626462633633346261353263306531623966383765663837663839
3463363738313530350a393535383065353266623939366261646261383034336434656134373035
61363265333437636561396564366335623336646136666166353862633565313135383262343033
33393966396239643938393935316338663563356638613438643263643731643139323439653733
36626363373465373430666565623431626337663265353435356132636232383938623437383232
35303061383064336237643737386239366531666661666666376331656462373537643936313135
33656666636366633262616636316263386136393533386533663633326261666237343939613632
37333561653465323633623232393863346233366631306333313433316363323266323433643666
61663737323639393265313136656462633831643536316636613366326139376166316531623532
37343232663931323033376230636263666562653238303339653930346230363262333665373365
64396337343265613734333536636534326631353630396465323337343063363932653437316133
35663063333366633463383062343766323261376531363263396637633335323131356661386238
66306336336435366562643463383065373631346265613931356637663638376661313363363764
34663764396434323232626262333431376435393666316233396434656439303133613232666138
65633636396338646163663866646264643536643563363338353338373066386130
