$ANSIBLE_VAULT;1.1;AES256
39636238323834313964313663333461336230356333646462313131373435393432653863336266
6265353737333966646337363537383031363365363133340a653839356137363733373538313939
39613838376631343233313635613164323630383365343463643232326339663131613434373831
6430396665396463330a383737633362323634363232616563343832306630303463633432306233
64613161613034366362663933343636393636666334376533383334386635363533383737643962
33633437643562363064363732663764356137366239303466353935393534336435663632663833
39643263313430333363636135623263343336333336383834613466383736363337616464653461
37323536373264326266623638396161376136643334313739343235303666653536336337333039
32386265373537633933393263613062383436303163353530656532343430323163373531666534
35336264303632313838346237386563616136323239333037653130623236323639346337613862
37633032653235633561396465656161366331363336343664313131363036393764653132313535
64653364633235656633363534353634323836393031623733643433653935643738636531386632
61346265343335316663386137316163643662313035343964613464396561333863333433386337
62646231386630376439393035343263396435346230326535306131376534353136653766316566
65303537363430363235646438383237303563326463326139616663646433336436353864313466
64323462326536663662666130333361383037366263386137663565313764623934376363613661
37666638373330353532363262313366616633653333323332343264316536623961
